### ISSUE TITLE
Fazer requisições na API do Github

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#17]
Fazer um código capaz de adiquirir dados do github

- [x] Pegar a API do Github.
- [ ] Fazer uma implementação capaz de pegar qualquer dado do Github.
- [x] Pegar os dados de um repositório.

**Comment by joao15victor08** [comment]
[Link](https://github.com/PyGithub/PyGithub) com uma biblioteca python interessante.
