### ISSUE TITLE
Iniciar documento de visão

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#20]
Fazer o documento visão para expressar a finalidade, o desenvolvimento e o andamento do projeto.

**Comment by ailamaralves** [comment]
referência: https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by ailamaralves** [comment]
https://docs.google.com/document/d/1aLlFy8nZM-urMBKWZgIqdGmFwP6__VZ-y03bjjuhy2U/edit#
