### ISSUE TITLE
Criar a logo

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#24]
### Criar a logo

Criar a logo do produto, definindo o símbolo, o design e a cor.

Nessa issue será realizado:
- Definir um símbolo que remeta ao nome e ao tema do projeto;
- Projetar um design para o símbolo esconlhido;
- Definir a cor.

Critérios de aceitação:
- [x] Tem um símbolo
- [ ] Tem um design criativo
- [ ] Estar colorida com uma justificativa.

**Comment by damarcones** [comment]
![dashowl_colorido](https://user-images.githubusercontent.com/27385254/65972353-1867b380-e440-11e9-96b8-caf3f8329c68.png)
