### ISSUE TITLE
Definir dados a serem filtrados

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#25]
### Definir dados a serem filtrados

Definir dados a serem filtrados da API do Github para o produto.

Nessa issue será realizado:
- Fazer uma lista de possíveis requisições;
- Fazer uma lista de quais dados se consegue pegar a partir do API do Github.

Critérios de aceitação:
- [x] Lista de possiveis requisições feita.
- [ ] Lista de quais dados de fato conseguimos recuperar.
- [x] Conseguir um match entre as listas de requisições e dados disponíveis.

**Comment by joao15victor08** [comment]
Dados selecionados [aqui](https://docs.google.com/document/d/10IMMSFno93iDVv-kEpbUcDrKNT5M-91D1XcYKqbNCEg/edit)
