### ISSUE TITLE
Criar novos repositórios

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#26]
### Criar novos repositórios

Criar novos repositórios para dividir o repositório em documentação e código.

Nessa issue será realizado:
- Criar um repositório para código;
- Definir como vai ser a divisão código e documentação.

Critérios de aceitação:
- [ ] Outro repositório criado.
- [ ] Divisão entre código e doc definidos.

**Comment by ailamaralves** [comment]
Criado: https://github.com/fga-eps-mds/2019.2-DashboardAgil
