### ISSUE TITLE
Criar documento de Arquitetura

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#31]
### Criar documento de Arquitetura

Criar documento de Arquitetura: escrever o documento que explique a arquitetura do nosso projeto.

Nessa issue será realizado:

- Escrever porque e como o nosso produto vai funcionar, cuprindo a estrutura da IBM.

Critérios de aceitação:

- [ ] Estar totalmente escrito;
- [x] Ter imagens e ilustrações;
- [x] Estar de acordo com a estrutura da IBM;
- [x] Ser revisado por todos.

**Comment by ailamaralves** [comment]
Iniciamos o documento aqui: https://docs.google.com/document/d/114KG0m-knVFblA1m68YUOpZ_FDjd6xDSIaH0CTkeHT8/edit#

**Comment by Matheus-AM** [comment]
### Precisamos ter um esborço do que vai ser usado no projeto.

- [ ] Definir como vão ser usadas as tecnologias escolhidas.
- [ ] Fazer uma revisão das tecnologias utilizadas.
- [ ] Um esborço do projeto.

**Comment by Matheus-AM** [comment]
O documento não está completo, mas está suficientemente preenchido com toda a arquitetura até a release 1 do projeto. O documento terá de ser atualizado para a release 2 e ter versão definitiva.
