### ISSUE TITLE
Esboço da interface	

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#33]
### Esboço da interface

Esboço da interface: planejar o design e desenhar uma interface para o produto.

Nessa issue será realizado:
- Planejar o design para o usuário;
- Desenhar o que o design sugere.

Critérios de aceitação:
- [x] Design definido para a tela de apresentação.
- [x] Desenhos da tela de apresentação.

**Comment by ailamaralves** [comment]
[Esboço das paginas](https://docs.google.com/document/d/10IMMSFno93iDVv-kEpbUcDrKNT5M-91D1XcYKqbNCEg/edit)
