### ISSUE TITLE
Criar extensão com o Google Chrome

### ISSUE THREAD

**Issue by Matheus-AM** [fga-eps-mds/2019.2-DashboardAgil-Wiki#37]
### Criar extensão com o Google Chrome

Criar extensão com o Google Chrome deve entregar a funcionalidade de extensão web pronta.

Nessa issue será realizado:
- Criar uma extensão para o Google Chrome;
- Deixa-lá funcionando da maneira desejada.

Critérios de aceitação:
- [x] Criar uma extensão para o Google Chrome.
- [x] Entregá-la pronta sem bugs

**Comment by KalebeLopes** [comment]
Fazer a extensão funcionar é bem tranquilo, mas para publicar na Chrome Web Store é necessário ter uma conta de desenvolvedor e pagar 5 dólares. Recomendo fazer a publicação quando ela estiver totalmente pronta.
Passo a passo para a publicação: https://developer.chrome.com/webstore/publish

**Comment by Matheus-AM** [comment]
A funcionalidade de extensão está funcionando no Google Chrome devidamente.
